# This is a basic workflow to help you get started with Actions
name: JMeter
on:
    push
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Jmeter
        run: echo Hola Mundo!!!
