# This is a basic workflow to help you get started with Actions
name: JMeter
on:
    push
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Curl
        run: sudo apt install curl
      - name: Temp
        run: sudo mkdir -p /tmp/jmeter/
      - name: Download JMeter
        run: sudo curl -L --silent https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.tgz > /tmp/jmeter/apache-jmeter-5.5.tgz
      - name: JMeter Folder
        run: sudo mkdir -p /home/jmeter/
      - name: Setup tzdata
        run: sudo apt install tzdata
      - name: JMeter tar
        run: sudo tar -xzf /tmp/jmeter/apache-jmeter-5.5.tgz -C /home/jmeter/
