# This is a basic workflow to help you get started with Actions
name: JMeter
on:
    push
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Curl
        run: apt install curl
      - name: Temp
        run: mkdir -p /tmpjmeter/
      - name: Download JMeter
        run: curl -L --silent https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.tgz > /tmp/jmeter/apache-jmeter-5.5.tgz
